core/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', views.index, name='index'),
    path('index1/', views.index1, name='index1'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('maquillaje/', ServiceListView.as_view(), name='maquillaje'),
    path('registro/', UserRegisterView.as_view(), name='registro'),
    path('services/create/', ServiceCreateView.as_view(), name='service_create'),
    path('service/<int:id>/', ServiceDetailView.as_view(), name='service_detail'),
    path('service/<int:id>/update', ServiceUpdateView.as_view(), name='service_update'),
    path('services/<int:id>/delete', ServiceDeleteView.as_view(), name='service_delete'),
    path('reservacion/', ReservationCreateView.as_view() , name='reservacion'),
    path('reservacion/success/<int:reservation_id>', ReservationSuccessView.as_view() , name='reservacion_success'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('mis-reservaciones/', ReservationListView.as_view(), name='mis_reservaciones'),
    path('reservation/<int:id>/delete', ReservationDeleteView.as_view(), name='reservation_delete'),
    path('completed-reservation/<int:id>', CompletedReservation.as_view(), name='reservacion_completada'),
    path('reservaciones/',ReservationListAdminView.as_view(), name="reservaciones"),
]

pagina_unas_an/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator

# Create your models here.

#-------------------------------------------------------------------
#Usuario
#-------------------------------------------------------------------
class User(AbstractUser):
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    addres = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    REQUIRED_FIELDS= ["phone_number"]

    class Meta:
        db_table= "users"
        verbose_name='Usuario'
        verbose_name_plural= 'Usuarios'

    def __str__(self):
        return f"{self.username} ({self.email})"


#-------------------------------------------------------------------
#Tipo de Servicio
#-------------------------------------------------------------------

class ServiceType(models.Model):
    name = models.CharField(max_length=200)
    class Meta:
        db_table= 'service_types'
        verbose_name = 'Tipo_Servicio'
        verbose_name_plural= 'Tipo_Servicios'
    
    def __str__(self):
        return (f'Tipo de Servicio: {self.name}')


#-------------------------------------------------------------------
#Servicio
#-------------------------------------------------------------------

class Service(models.Model):
    service_type = models.ForeignKey(ServiceType, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(
        verbose_name='Descripcion detalla',
        max_length= 500,
        blank=True,
        null=True
    )

    image = models.ImageField(
        verbose_name= 'Imagen',
        upload_to= 'core/services',
        validators=[FileExtensionValidator(allowed_extensions=['jpg','jpeg','png','webp'])],
        blank= True,
        null=True
    )
    class Meta:
        db_table = 'services'
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'
        
    def __str__(self):
        return f"El servicio de {self.name} tiene un precio  de {self.price} "
    
    def delete(self, *args, **kwargs):
        if self.image:
            self.image.delete() #borra el archivo fisico del disco
        super().delete(*args, **kwargs)  #borra el registro del modelo de la DB

#-------------------------------------------------------------------
#Reservacion
#-------------------------------------------------------------------

class Reservation(models.Model):
    user = models.ForeignKey(User,on_delete=models.PROTECT,related_name='reservations')
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    reservation_date = models.DateField()
    reservation_time = models.TimeField()
    completed = models.BooleanField(default=False)

    class Meta:
        db_table = 'reservations'
        verbose_name = 'Reservación'
        verbose_name_plural = 'Reservaciones'       

    def __str__(self):
        return f"Reservación #{self.id} - {self.user.first_name} {self.user.last_name} - {self.total_price}"


#-------------------------------------------------------------------
#Servicio Reservacion
#-------------------------------------------------------------------

class ServiceReservation(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)

    class Meta:
        db_table = 'service_reservations'
        unique_together= [['service', 'reservation']]

    def __str__(self):
        return f"{self.service.name} tiene un precio total de {self.service.price} "
    

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
class LoginForm(forms.Form):
    username = forms.CharField(
        label="Nombre de Usuario",
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'Tu Nombre de Usuario', 'class': 'main__input'})
    )

    password = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={'placeholder':'Tu Contraseña', 'class': 'main__input'})
    )

User = get_user_model()
class RegisterForm(forms.Form):
    username = forms.CharField(
        label="Nombre de Usuario",
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'Define tu nombre de usuario', 'class': 'main__input'})
    )

    email = forms.EmailField(
        label="Correo Electronico",
        widget=forms.EmailInput(attrs={'placeholder': 'tu@email.com', 'class': 'main__input'})
    )

    password = forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={'placeholder': 'Introduce tu contraseña', 'class': 'main__input'})
    )

    password_confirm = forms.CharField(
        label="Confirmar contraseña",
        widget=forms.PasswordInput(attrs={'placeholder': 'Repite tu contraseña', 'class': 'main__input'})
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError("Este nombre de usuario ya esta en uso.")
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este correo electronico ya esta registado.")
        return email
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise ValidationError("Las contraseñas no coinciden.")
        return cleaned_data
    

core/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Service, ServiceType, Reservation, ServiceReservation
from django.views import View
from django.db.models import Sum, Q
from django.http import HttpResponse
from datetime import date
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, get_user_model, logout
from .forms import LoginForm, RegisterForm
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def index1(request):
    return render(request, 'core/index1.html')

class ServiceCreateView(LoginRequiredMixin,View):
    template_name = 'core/servicio.html'

    def get(self, request, *args, **kwargs):
        service_types = ServiceType.objects.all()
        if request.user.is_authenticated:
            return redirect('login')
        return render(request, self.template_name, {'service_types' : service_types})
    
    def post(self, request, *args, **kwargs):
        name= request.POST.get("name")
        price=request.POST.get("price")
        description=request.POST.get("description", "")
        service_type_id= request.POST.get("service_type")
        service = ServiceType.objects.filter(id=service_type_id).first() if service_type_id else None
        image_file = request.FILES.get('image')
        image = image_file
        errors = {} #diccionario para errores por campo

        if not name:
            errors['name'] = "El nombre es requerido"

        if not service:
            errors['service'] = "El servicio es requerido"

        if not price:
            errors['price'] = "El precio es requerido"

        if not image:
            errors['image'] = "La imagen es requerida"

        if errors:
            service_types = ServiceType.objects.all()
            return render( request, self.template_name, {
                'service_types': service_types,
                'errors': errors,
            })

        new_service = Service.objects.create(
            name=name,
            price=price,
            description=description,
            service_type=service,
            image=image
            
        )
        return redirect('maquillaje')


class ServiceListView(View):
    template_name = 'core/maquillaje.html'
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        service_type =request.GET.get('service_type')
        services = Service.objects.all()

        if query:
            services = services.filter(
                Q(name__icontains=query)  |
                Q(description__icontains=query)   |
                Q(price__icontains=query)
            ).distinct()
        
        if service_type:
            services = services.filter(service_type__id=service_type)

        paginator = Paginator(services, self.paginate_by)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        query_dict=request.GET.copy()
        if 'page' in query_dict:
            del query_dict['page']
        url_params=query_dict.urlencode()

        context = {
            'page_obj': page_obj,
            'services' : page_obj.object_list,
            'query' : query,
            'service_types': ServiceType.objects.all(),
            'service_type': ServiceType.objects.filter(id=service_type).first() if service_type else None, 
            'url_params': url_params
        }
        return render(request, self.template_name, context)
    

class ServiceDetailView(View):
    template_name = 'core/service_detail.html'

    def get(self, request, id, *args, **kwargs):
        #get object or 404 es una buena practica para manejar productos no encontrados
        service = get_object_or_404(Service, id=id)
        return render(request, self.template_name, {'s': service})
    

class ServiceUpdateView(View):
    template_name = 'core/service_update.html'

    def get(self, request, id, *args, **kwargs):
        service = get_object_or_404(Service, id=id)
        service_types = ServiceType.objects.all()  #necesario para el select de servicio
        return render(request, self.template_name, {'service': service, 'service_types': service_types})
    
    def post(self, request, id,*args, **kwargs):
        service = get_object_or_404(Service, id=id)
        name= request.POST.get("name")
        price=request.POST.get("price")
        description=request.POST.get("description", "")
        service_type_id= request.POST.get("service_type")
        service_type= ServiceType.objects.filter(id=service_type_id).first() if service_type_id else None
        new_image_file = request.FILES.get('image')

        service.name = name
        service.price=price
        service.description=description
        service.service_type=service_type
        if new_image_file:
            if service.image and service.image.name:
                service.image.delete(save=False)
                #save=false previene que se guarde el modelo de antes
                #asignar la nueva imagen al campo del modelo
            service.image= new_image_file
        service.save()

        return redirect('maquillaje')
    
class ServiceDeleteView(View):
    template_name = 'core/service_confirm_delete.html'

    def get(self, request, id, *args, **kwargs):
        service = get_object_or_404(Service, id=id)

        return render(request, self.template_name, {'service': service})
    
    def post(self, request, id, *args, **kwargs):
        try:
            service = get_object_or_404(Service, id=id)
            service.delete()
        #redirige a la lista de servicios despues de la eliminacion
            return redirect('maquillaje')
        except Exception as e:
            return HttpResponse("No se puede eliminar el servicio")



    
class ReservationCreateView(LoginRequiredMixin,View):
    template_name = 'core/reservacion.html'

    def get(self, request, *args, **kwargs):
        services = Service.objects.all()
        today= date.today().strftime('%Y-%m-%d')
        return render(request, self.template_name, {
            'services' : services, 'today': today
        })
    
    def post(self, request, *args, **kwargs):

        current_user = request.user

        reservation_date= request.POST.get("reservation_date")
        reservation_time=request.POST.get("reservation_time")

        selected_services_ids = request.POST.getlist('services')

        selected_services =Service.objects.filter(id__in=selected_services_ids)

        print(selected_services)

        total_price = selected_services.aggregate(Sum('price'))['price__sum'] or 0
        print(total_price)


        new_reservation = Reservation.objects.create(
            reservation_date = reservation_date,
            reservation_time = reservation_time,
            total_price= total_price,
            user= current_user
        )

        for service in selected_services:
            ServiceReservation.objects.create(
                reservation=new_reservation,
                service=service
            )
        
        return render(request, 'core/reservacion_success.html', {'reservation':new_reservation})

class ReservationSuccessView(View):
    # template_name = 'core/reservacion.html'

    def get(self, request,reservation_id, *args, **kwargs):
        reservation = Reservation.objects.get(id=reservation_id)
        return HttpResponse(reservation)
        # return render(request, self.template_name, {'reservations' : reservation})

class UserLoginView(View):
    template_name = 'core/login.html'

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        if request.user.is_authenticated:
            return redirect('maquillaje')
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('maquillaje')
            else:
                return render(request, self.template_name, {
                    'form': form,
                    'error_message': 'Nombre de Usuario o Contraseña Incorrectos.'
                })
        return render(request, self.template_name, {'form': form})
    

class UserRegisterView(View):
    template_name = 'core/registro.html'

    def get(self, request, *args, **kwargs):
        form = RegisterForm()
        if request.user.is_authenticated:
            return redirect('maquillaje')
        return render(request, self.template_name, {'form': form})
    
    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            User = get_user_model()
            user = User.objects.create_user(username=username, email=email, password=password)

            login(request, user)

            return redirect('maquillaje')
        
        return render(request, self.template_name, {'form': form})
    
class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)

        return redirect('login')
    

class ReservationListView(View):
    template_name = 'core/mis_reservaciones.html'
    paginate_by = 3 

    def get(self,request, *args, **kwargs):
        query = request.GET.get('q')
        current_user = request.user
        reservations = Reservation.objects.filter(user=current_user)

        if query:
            reservations = reservations.filter(total_price=query)

core/templates/core/Pagina _Uñas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="index.css">
    <title>AN Studio</title>
</head>
<body>
    <header class="header1">
        <div class="menu">
            <img src="img/logoo3.png" alt="logo">

            <nav class="nav1">
                <ul>
                    <li><a href="#inicio">Inicio</a></li>
                    <li><a href="">Servicios</a>
                    <ul>
                        <li><a href="index1.html">Manicure y Pedicure</a></li>
                        <li><a href="maquillaje.html">Maquillaje</a></li>
                    </ul>
                    </li>
                    <li><a href="">Reservaciones</a>
                    <ul>
                        <li><a href="login.html">Solicitar Cita</a></li>
                    </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    
    <main>
        <section class="hero">
            <div class="hero-text">
                <h1>Bienvenidas al Salon de Belleza AN Studio.</h1>
                <p>Las mejores uñas y los mejores maquillajes para los mejores momentos.</p>
            </div>
        </section>

        <div class="info-section">
            <h2>¿Porque elegirnos?</h2>
            <p>En AN Studio nos dedicamos a brindarte la mejor experiencia en cuidado de uñas y maquillaje profesional. Nos encargamos de ultilizar productos de alta calidad y tecnicas innovadoras para garantizar resultados espectaculares. </p>
            <p>Ofrecemos un ambiente relajante y acogedor donde podras disfrutar de un momento de autocuidado mientras tu uñas en obras de arte y dejamos tu piel radiante. </p>            </div>
        </div>

        <div class="galeria">
            <h2> Galería de Trabajos.</h2>
        </div>
        
        <div class="gallery">
        <div class="gallery-item">
            <img src="img/unas123.png" alt="Manicura">
        </div>
        <div class="gallery-item">
            <img src="img/maquillaje2.jpeg" alt="Maquillaje">
        </div>
        <div class="gallery-item">
            <img src="img/pedicure.jpeg" alt="Pedicure">
        </div>
        </div>
    </main>

    <footer class="footer">
        <div class="footer-content container">
            <div class="link">
                <h3>Contactanos</h3>
                <ul>
                    <li><a href="#">Email:an_studio@gmail.com</a></li>
                    <li><a href="#">Telefono: 0412 0697586</a></li>
                    <li><a href="#">Direccion: calle principal</a></li>
                </ul>
            </div>

            <div class="link">
                <h3>Enlaces</h3>
                <ul>
                    <li><a href="#">Sobre nosotros</a></li>
                    <li><a href="#">Servicios</a></li>
                    <li><a href="#">Contactos</a></li>
                </ul>
            </div>
            <div class="link">
                <h3>Siguenos</h3>
                <ul>
                    <li><a href="https://facebook.com">Facebook</a></li>
                    <li><a href="https://instagram.com">Instagram</a></li>
                    <li><a href="https://twitter">Twitter</a></li>
                </ul>
            </div>
        </div>
        <a href="#" id="btn-arriba">↑</a>
    </footer>
</body>
</html>

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block css_styles %}
        <link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
    {% endblock css_styles %}
    <title>{% block title %}AN Studio{% endblock %} </title>
</head>
<body>
    <header class="header1">
        <div class="menu">
            <img src="{% static 'core/img/logoo3.png' %}" alt="logo">

            <nav class="nav1">
                <ul>
                    <li><a href="{% url 'index' %}">Inicio</a></li>
                    <li><a href="{% url 'maquillaje' %}">Servicios</a>
                    </li>
                    {% if user.is_authenticated and not user.is_staff %}
                        <li><a href="{% url 'mis_reservaciones' %}">Mis Reservaciones</a></li>
                    {% elif user.is_authenticated and user.is_staff %}
                        <li><a href="{% url 'reservaciones' %}">Reservaciones</a></li>
                    {% endif %}

                    <li class="user-auth">
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="btn-cerrar-sesion"> ✦Bienvenida, {{ user.username }}! Cerrar sesión</a>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}" class="btn-iniciar-sesion">Iniciar sesión</a>
                        </li>
                        <li>
                            <a href="{% url 'registro' %}" class="btn-iniciar-sesion">Registrarse</a>
                        </li>
                    {% endif %}
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <main>
        {% block content %}
            {% endblock %}
    </main>

    <footer class="footer">
        <div class="footer-content container">
            <div class="link">
                <h3>Contactanos</h3>
                <ul>
                    <li><a href="#">Email:an_studio@gmail.com</a></li>
                    <li><a href="#">Telefono: 0412 0697586</a></li>
                    <li><a href="#">Direccion: calle principal</a></li>
                </ul>
            </div>

            <div class="link">
                <h3>Enlaces</h3>
                <ul>
                    <li><a href="#">Sobre nosotros</a></li>
                    <li><a href="#">Servicios</a></li>
                    <li><a href="#">Contactos</a></li>
                </ul>
            </div>
            <div class="link">
                <h3>Siguenos</h3>
                <ul>
                    <li><a href="https://facebook.com">Facebook</a></li>
                    <li><a href="https://instagram.com">Instagram</a></li>
                    <li><a href="https://twitter">Twitter</a></li>
                </ul>
            </div>
        </div>
        <a href="#" id="btn-arriba">↑</a>
    </footer>

</body>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}
{% block css_styles %}
        <link rel="stylesheet" href="{% static 'core/css/index.css' %}">
        {{ block.super }}
    {% endblock css_styles %}

{% block content %}
    <section class="hero">
        <div class="hero-text">
            <h1>Bienvenidas al Salon de Belleza AN Studio.</h1>
            <p>Las mejores uñas y los mejores maquillajes para los mejores momentos.</p>
        </div>
    </section>

    <div class="info-section">
        <h2>¿Porque elegirnos?</h2>
        <p>En AN Studio nos dedicamos a brindarte la mejor experiencia en cuidado de uñas y maquillaje profesional. Nos encargamos de ultilizar productos de alta calidad y tecnicas innovadoras para garantizar resultados espectaculares. </p>
        <p>Ofrecemos un ambiente relajante y acogedor donde podras disfrutar de un momento de autocuidado mientras tu uñas en obras de arte y dejamos tu piel radiante. </p>            </div>
    </div>

    <div class="galeria">
        <h2> Galería de Trabajos.</h2>
    </div>

    <div class="gallery">
        <div class="gallery-item">
            <img src="{% static 'core/img/unas123.png' %}" alt="Manicura">
        </div>
        <div class="gallery-item">
            <img src="{% static 'core/img/maquillaje2.jpeg' %}" alt="Maquillaje">
        </div>
        <div class="gallery-item">
            <img src="{% static 'core/img/pedicure.jpeg' %}" alt="Pedicure">
        </div>
    </div>
{% endblock %}

core/templates/core/index1.html
{% extends "core/base.html" %}
{% load static %}

{% block css_styles %}
        <link rel="stylesheet" href="{% static 'core/css/index1.css' %}">
        {{ block.super }}
{% endblock css_styles %}

{% block title %} Manicure y Pedicure {% endblock %}

{% block content %}
    <div id="services" class="page"> 
        <h1>Manicure y Pedicure</h1>        

        <div class="services-grid">
            <div class="service-card">
                <img src="{% static 'core/img/clasica.jpeg' %}" alt="Manicura Clasica">
                <h3>Manicura Clasica</h3>
                <p>Limado, pulido, cuticula y esmalte tradicional. Incluye hidratacion en manos y masajes relajantes.</p>
                <p class="precio">$15</p>
        </div>

        <div class="service-card">
            <img src="{% static 'core/img/gel.jpeg' %}" alt="Manicura Gel.">
            <h3>Manicura en Gel</h3>
            <p>Esmaltado semipermanente, que dura hasta 3 semanas. Acabado brillante y resistente a golpes.</p>
            <p class="precio">$25</p>
        </div>

        <div class="service-card">
            <img src="{% static 'core/img/acrilicas.jpeg' %}" alt="Manicura Acrilicas">
            <h3>Uñas Acrilicas</h3>
            <p>Extensiones y esculpido de uñas con acrilico. Diseño personalizados segun tus preferencias.</p>
            <p class="precio">$30</p>
        </div>

        <div class="service-card">
            <img src="{% static 'core/img/pedicure.jpeg' %}" alt="Pedicura">
            <h3>Pedicure</h3>
            <p>Incluye esmaltado semipermanente y masaje.</p>
            <p class="precio">$15</p>
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/css/login.css' %}">
    <title>Login</title>
</head>
<body>
    <header>
        <nav><a href="{% url 'index' %}">Volver</a></nav>
    </header>
    <section class="main">

        <figure class="main__figure">
            <img src="{% static 'core/img/login1.png' %}" class="main__img">
        </figure>

        <div class="main__contact">
            <h2 class="main__title">¡Hola de nuevo!</h2>
            <p class="main__paragraph">¡Bienvenidas cuanto tiempo!</p>

            <form method="post" action="{% url 'login' %}" class="main__form">
                {% csrf_token %}

                {{ form.username }}

                {{ form.password}}
                {% if error_message %}
                    <p style="color: red;">{{ error_message}}</p>
                {% endif %}
                <button type="submit" class="main__input main__input--send">Iniciar Sesion</button>

            </form>
            <p> ¿Es la primera vez que estas aqui?</p>
            <p class="main__paragraph"><a href="{% url 'registro' %}">Crea una cuenta</a></p>

            <article class="main__social">
                <a href="#" class="main__link">
                    <img src="{% static 'core/img/panorama.png' %}" class="main__icon">
                </a>

                <a href="#" class="main__link">
                    <img src="{% static 'core/img/cromo.png' %}" class="main__icon">
                </a>

                <a href="#" class="main__link">
                    <img src="{% static 'core/img/logotipo-de-apple.png' %}" class="main__icon">
                </a>
            </article>
        </div>
    </section>

</body>
</html>

core/templates/core/reservacion.html
{% extends "core/base.html" %}
{% load static %}

{% block css_styles %}
    <link rel="stylesheet" href="{% static 'core/css/reservacion.css' %}">
    {{ block.super }}
{% endblock css_styles %}

{% block content %}

<form method="post" action="{% url 'reservacion' %}">
    {% csrf_token %}
    <fieldset>
    <div id="reservacion" class="page">
        <div class="reservacion-from">
            <h2>Agendar cita</h2>

            <div class="form-group">
                <label for="services">Selecciona los Servicios:</label>
                <select id="services" name="services" multiple required>
                    {% for service in services %}
                        <option value="{{service.id}}">{{ service.name }} - ${{ service.price }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label for="reservation_date">Fecha Preferida</label>
                <input type="date" id="reservation_date" name="reservation_date" 
                    min= "{{ today }}" required>
            </div>

            <div class="form-group">
                <label for="reservation_time">Hora Preferida</label>
                <input type="time" id="reservation_time" name="reservation_time" required>
            </div>

            <button type="submit" class="submit-btn">Reservar Cita</button>
</form>
        </div>
    </div>
{% endblock %}

core/templates/core/service_confirm_delete.html
<div id="modal-{{ s.id }}" class="modal-overlay">
    <section class="modal-content">
        {% if s.servicereservation_set.all %}
            <div class="modal-buttons">
                <p>No se puede eliminar el servicio</p>
                <a href="#" class="button-cancel">Cancelar</a>
            </div>    
        {% else %}
            <h1>¿Estás seguro de que quieres eliminar "{{ s.name }}"?</h1>
            <p>Esta acción no se puede deshacer.</p>

            <form method="post" action="{% url 'service_delete' id=s.id %}">
                {% csrf_token %}
                <div class="modal-buttons">
                    <button type="submit" class="button-delete">Eliminar</button>
                    <a href="#" class="button-cancel">Cancelar</a>
                </div>
            </form>
        {% endif %}
    </section>
</div>